version: '3'

services:
  app:
    image: registry.cn-shenzhen.aliyuncs.com/luler/linux_php_nginx:libreoffice
    ports:
      - 8080:8000
    restart: always
    privileged: true
    volumes:
      - .:/app